FROM python:3.9-slim-buster

RUN apt-get update && apt-get install -y --no-install-recommends \
    git \
    && rm -rf /var/lib/apt/lists/*

RUN pip install --upgrade pip && pip install dbt

RUN pip install -r requirements.txt

WORKDIR /usr/app

COPY . .
COPY dbt_project.yml .
COPY profiles.yml /root/.dbt/

CMD ["dbt", "run"]