version: "3.8"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  dbt:
    image: fishtownanalytics/dbt:0.21.0
    container_name: dbt
    volumes:
      - ./dbt:/usr/app/dbt
    depends_on:
      - postgres
    environment:
      DBT_PROFILES_DIR: /usr/app/dbt
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: gpdata
      POSTGRES_HOST: localhost
      POSTGRES_PORT: 5432

  metabase:
    image: metabase/metabase:v0.41.1
    container_name: metabase
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  prefect-server:
    image: prefecthq/server:latest
    container_name: prefect-server
    depends_on:
      - postgres
    environment:
      - PREFECT__SERVER__DATABASE__URI=postgresql://root:root@localhost:5432/prefect

  prefect-ui:
    image: prefecthq/ui:latest
    container_name: prefect-ui
    ports:
      - "8080:8080"
    depends_on:
      - prefect-server

  prefect-agent:
    image: prefecthq/prefect:0.15.4-python3.8
    container_name: prefect-agent
    environment:
      PREFECT__CLOUD__AGENT__AUTH_TOKEN: ""
      PREFECT__CLOUD__API__KEY: ""
      PREFECT__CLOUD__AGENT__LABELS: '["dbt", "metabase"]'
      PREFECT__CLOUD__API__URL: http://prefect-server:4200
    depends_on:
      - prefect-server
      - postgres

volumes:
  db-data:
